const CATEGORIES_ACTION_TYPES = {
  // SET_CATEGORIES_MAP: 'category/SET_CATEGORIES_MAP',
  // SET_CATEGORIES: 'category/SET_CATEGORIES',
  SET_CATEGORIES_START: 'category/FETCH_CATEGORIES_START',
  SET_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
  SET_CATEGORIES_FAILED: 'category/FETCH_CATEGORIES_FAILED'
};

export default CATEGORIES_ACTION_TYPES;